server:
  port: 8001

spring:
  application:
    name: itpm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://www.hixinj.com:13306/itpm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "${mysql_itpm_password}"
    druid:
      test-while-idle: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pm.entities


pm:
  jwt:
    secret: "${jwt_secret}"
      # token有效时长，7天，单位秒
    expire: 1296000
    header: authorization